-- ASLAN foundational production schema
create extension if not exists pgcrypto;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null default '',
  price_dzd numeric(12,2),
  stock integer not null default 0 check (stock >= 0),
  active boolean not null default true,
  images jsonb not null default '[]'::jsonb,
  category_id bigint references public.categories(id) on delete set null,
  features jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user','admin')),
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  type text not null,
  name text not null,
  phone text not null,
  message text not null,
  product_id bigint references public.products(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'new' check (status in ('new','contacted','qualified','closed')),
  created_at timestamptz not null default now()
);

create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists products_active_created_at_idx on public.products(active, created_at desc);
create index if not exists leads_created_at_idx on public.leads(created_at desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

insert into public.categories (name, slug) values
  ('تنجيد', 'upholstery'),
  ('خياطة وتفصيل', 'sewing'),
  ('ديكور', 'decor')
on conflict (slug) do nothing;

insert into public.products (name, slug, description, price_dzd, stock, active, images, category_id, features)
select
  'كرسي ASLAN',
  'aslan-chair',
  'كرسي بتنجيد مخصص وتشطيب ASLAN.',
  9500,
  0,
  true,
  '[]'::jsonb,
  c.id,
  '{"width_cm":45,"seat_height_cm":43,"seat_foam_density":30}'::jsonb
from public.categories c
where c.slug = 'upholstery'
on conflict (slug) do nothing;

alter table public.categories enable row level security;
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.leads enable row level security;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = auth, public, pg_temp
as $$
  select coalesce(
    (select raw_app_meta_data ->> 'role' from auth.users where id = (select auth.uid())),
    ''
  ) = 'admin'
  or exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

revoke all on function private.is_admin() from public;
grant execute on function private.is_admin() to authenticated;

drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories for select to anon, authenticated using (true);

drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products for select to anon, authenticated using (active = true);
drop policy if exists products_admin_insert on public.products;
create policy products_admin_insert on public.products for insert to authenticated with check ((select private.is_admin()));
drop policy if exists products_admin_update on public.products;
create policy products_admin_update on public.products for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
drop policy if exists products_admin_delete on public.products;
create policy products_admin_delete on public.products for delete to authenticated using ((select private.is_admin()));

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select to authenticated using (id = (select auth.uid()) or (select private.is_admin()));
drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));

drop policy if exists leads_public_insert on public.leads;
create policy leads_public_insert on public.leads for insert to anon, authenticated with check (length(type) between 1 and 50 and length(name) between 2 and 120 and length(phone) between 6 and 30 and length(message) between 5 and 4000);
drop policy if exists leads_admin_read on public.leads;
create policy leads_admin_read on public.leads for select to authenticated using ((select private.is_admin()));
drop policy if exists leads_admin_update on public.leads;
create policy leads_admin_update on public.leads for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
drop policy if exists leads_admin_delete on public.leads;
create policy leads_admin_delete on public.leads for delete to authenticated using ((select private.is_admin()));
